name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version

      # Step 3: Build a Docker image with Playwright
      - name: Build Playwright Docker image
        run: |
          docker build -t playwright-tests .

      # Step 4: Run Playwright tests in Docker
      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
          -v $(pwd):/app \
          -w /app \
          playwright-tests \
          npx playwright test

      # Step 5: Upload Playwright report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
